#!/bin/bash
#This is a simple way of commiting on Github

echo -n "Enter your comment: "
read comment
echo "You entered: $comment"

git add *
git add -u :/
git commit -m "$comment"
git push origin master
